### ISSUE TITLE
Unauthorized 401

### ISSUE THREAD

**Issue by DShawnB** [fuzzzerd/fmDotNet#2]
When I use your dll from NugGet I can connect to the FMServer_Sample database with no issue. However, if I try to connect to any other database I get a 401-unauthorized. The user that I am using have full privs and fmxml is turned on. Any suggestions?

**Comment by fuzzzerd** [comment]
Could be an issue with the name of your file. FMS12 seemed to handle file names differently, especially when the name has spaces. Did your file have any odd characters in the name? Spaces? Extra periods?
