### ISSUE TITLE
database name lenght limit

### ISSUE THREAD

**Issue by codicebinario** [fuzzzerd/fmDotNet#3]
Is there a filemaker database naming lenght limit?
Enrico

**Comment by fuzzzerd** [comment]
I am not aware of any such limitation from FileMaker; however, I expect it would be dictated by the underlying file system, in either Mac or Windows. As far as fmDotNet is concerned, any database that is hosted by FMS should be handled by fmDotNet.

If you're having a specific issue with fmDotNet not handling long file names, please share some more specifics on the environemnt and the database in question.

**Comment by codicebinario** [comment]
Hi we have a database name longer than 25 char and 4 _ 
We received this error The file: "db_richieste_web_culturali_2018" is not available.
We rename it and shorter the name under 25 used only 3 _ and it worked. Fm server 16 is on a Windows server.

**Comment by fuzzzerd** [comment]
Are you able to hit the database through the XML API manually with something like Postman?
